name: Migrate Database

on:
  workflow_call:

jobs:
  run-migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: |
          echo "Hello world"
