name: Deploy Assistant

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy"
        required: true
        default: "assistant-v0.0.1"
      image_name:
        description: "Image name"
        required: true
        default: "assistant"
      context:
        description: "Context"
        required: true
        default: "./assistant"
      file:
        description: "File"
        required: true
        default: "./assistant/Dockerfile"

permissions:
  contents: read
  packages: write

jobs:
  test-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - run: |
          echo "Testing assistant in staging..."

  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - run: |
          echo "Deploying assistant to staging..."

  wait-for-production-approval:
    runs-on: ubuntu-latest
    environment: production-approval
    needs: test-staging
    steps:
      - run: |
          echo "Waiting for production approval..."

  test-production:
    runs-on: ubuntu-latest
    environment: production
    needs: wait-for-production-approval
    steps:
      - run: |
          echo "Testing assistant in production..."

  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    needs: wait-for-production-approval
    steps:
      - run: |
          echo "Deploying assistant to production..."

  # call-build-docker-image:
  #   uses: ./.github/workflows/reusable-build-docker.yml
  #   with:
  #     image-name: ${{ inputs.image_name }}
  #     version: ${{ inputs.version }}
  #     context: ${{ inputs.context }}
  #     file: ${{ inputs.file }}
  # debug:
  #   runs-on: ubuntu-latest
  #   needs: call-build-docker-image
  #   steps:
  #     - run: |
  #         echo "Image name: ${{ needs.call-build-docker-image.outputs.image-name-with-digest }}"
