name: Deploy Assistant

on:
  workflow_dispatch:
    inputs:
      infrastructure-changed:
        description: "Infrastructure changed"
        required: true
        type: boolean
      migrations-changed:
        description: "Migrations changed"
        required: true
        type: boolean
      assistant-changed:
        description: "Assistant changed"
        required: true
        type: boolean
      knowledge-changed:
        description: "Knowledge changed"
        required: true
        type: boolean

permissions:
  contents: read
  packages: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      infrastructure-changed: ${{ inputs.infrastructure-changed }}
      migrations-changed: ${{ inputs.migrations-changed }}
      assistant-changed: ${{ inputs.assistant-changed }}
      knowledge-changed: ${{ inputs.knowledge-changed }}
    steps:
      - run: |
          echo "Detecting changes..."
          echo "Infrastructure changed: ${{ inputs.infrastructure-changed }}"
          echo "Migrations changed: ${{ inputs.migrations-changed }}"
          echo "Assistant changed: ${{ inputs.assistant-changed }}"
          echo "Knowledge changed: ${{ inputs.knowledge-changed }}"

  provision-infrastructure-staging:
    runs-on: ubuntu-latest
    environment: staging
    needs: detect-changes
    if: |
      needs.detect-changes.outputs.infrastructure-changed == 'true'
    steps:
      - run: |
          echo "Provisioning infrastructure..."

  apply-migrations-staging:
    runs-on: ubuntu-latest
    needs: [detect-changes, provision-infrastructure-staging]
    if: |
      (always() && needs.detect-changes.outputs.migrations-changed == 'true' &&
      (needs.provision-infrastructure-staging.result == 'success' || needs.provision-infrastructure-staging.result == 'skipped'))
    environment: staging
    steps:
      - run: |
          echo "Applying migrations..."

  build-assistant-image:
    uses: ./.github/workflows/reusable-build-docker.yml
    needs: [detect-changes, apply-migrations-staging]
    if: |
      (always() && needs.detect-changes.outputs.assistant-changed == 'true' &&
      (needs.apply-migrations-staging.result == 'success' || needs.apply-migrations-staging.result == 'skipped'))
    with:
      image-name: aiasst-api
      context: ./assistant
      file: ./assistant/Dockerfile

  deploy-assistant-image-staging:
    runs-on: ubuntu-latest
    environment: staging
    needs: [build-assistant-image]
    if: needs.build-assistant-image.result == 'success'
    outputs:
      image-name-with-digest: ${{ needs.build-assistant-image.outputs.image-name-with-digest }}
    steps:
      - run: |
          echo "Deploying assistant image ${{ needs.build-assistant-image.outputs.image-name-with-digest }} to staging..."

  build-cleanup-job-image:
    uses: ./.github/workflows/reusable-build-docker.yml
    needs: [detect-changes, apply-migrations-staging]
    if: |
      (always() && needs.detect-changes.outputs.assistant-changed == 'true' &&
      (needs.apply-migrations-staging.result == 'success' || needs.apply-migrations-staging.result == 'skipped'))
    with:
      image-name: aiasst-cleanup-job
      context: ./assistant
      file: ./assistant/Dockerfile.ConversationCleanupJob

  deploy-cleanup-job-image-staging:
    runs-on: ubuntu-latest
    environment: staging
    needs: [build-cleanup-job-image]
    if: needs.build-cleanup-job-image.result == 'success'
    outputs:
      image-name-with-digest: ${{ needs.build-cleanup-job-image.outputs.image-name-with-digest }}
    steps:
      - run: |
          echo "Deploying cleanup job image ${{ needs.build-cleanup-job-image.outputs.image-name-with-digest }} to staging..."

  build-knowledge-image:
    uses: ./.github/workflows/reusable-build-docker.yml
    needs: [detect-changes, apply-migrations-staging]
    if: |
      (always() && needs.detect-changes.outputs.knowledge-changed == 'true' &&
      (needs.apply-migrations-staging.result == 'success' || needs.apply-migrations-staging.result == 'skipped'))
    with:
      image-name: aiasst-knowledge
      context: ./knowledge-search
      file: ./knowledge-search/Dockerfile

  deploy-knowledge-image-staging:
    runs-on: ubuntu-latest
    environment: staging
    needs: [build-knowledge-image]
    if: needs.build-knowledge-image.result == 'success'
    outputs:
      image-name-with-digest: ${{ needs.build-knowledge-image.outputs.image-name-with-digest }}
    steps:
      - run: |
          echo "Deploying knowledge image ${{ needs.build-knowledge-image.outputs.image-name-with-digest }} to staging..."

  wait-for-production-approval:
    runs-on: ubuntu-latest
    environment: production-approval
    needs:
      [
        deploy-assistant-image-staging,
        deploy-cleanup-job-image-staging,
        deploy-knowledge-image-staging,
      ]
    steps:
      - run: |
          echo "Waiting for production approval..."

  provision-infrastructure-production:
    runs-on: ubuntu-latest
    environment: production
    needs: [detect-changes, wait-for-production-approval]
    if: |
      needs.detect-changes.outputs.infrastructure-changed == 'true'
    steps:
      - run: |
          echo "Provisioning infrastructure..."

  apply-migrations-production:
    runs-on: ubuntu-latest
    needs: [detect-changes, provision-infrastructure-production]
    environment: production
    if: |
      (always() && needs.detect-changes.outputs.migrations-changed == 'true' &&
      (needs.provision-infrastructure-production.result == 'success' || needs.provision-infrastructure-production.result == 'skipped'))
    steps:
      - run: |
          echo "Applying migrations..."

  test-production:
    runs-on: ubuntu-latest
    environment: production
    needs:
      [
        wait-for-production-approval,
        provision-infrastructure-production,
        apply-migrations-production,
      ]
    steps:
      - run: |
          echo "Testing assistant in production..."

  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    needs:
      [
        test-production,
        provision-infrastructure-production,
        apply-migrations-production,
        deploy-assistant-image-staging,
        deploy-cleanup-job-image-staging,
        deploy-knowledge-image-staging,
      ]
    steps:
      - run: |
          echo "Deploying assistant to production..."
          echo "assistant: ${{ needs.deploy-assistant-image-staging.outputs.image-name-with-digest }}"
          echo "cleanup-job: ${{ needs.deploy-cleanup-job-image-staging.outputs.image-name-with-digest }}"
          echo "knowledge: ${{ needs.deploy-knowledge-image-staging.outputs.image-name-with-digest }}"

  # debug:
  #   runs-on: ubuntu-latest
  #   needs: call-build-docker-image
  #   steps:
  #     - run: |
  #         echo "Image name: ${{ needs.call-build-docker-image.outputs.image-name-with-digest }}"
