name: Deploy Assistant

on:
  workflow_dispatch:
    inputs:
      infrastructure:
        description: "Infrastructure changed"
        required: true
        type: boolean
      migrations:
        description: "Migrations changed"
        required: true
        type: boolean
      assistant:
        description: "Assistant changed"
        required: true
        type: boolean
      knowledge:
        description: "Knowledge changed"
        required: true
        type: boolean

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      infrastructure: ${{ inputs.infrastructure }}
      migrations: ${{ inputs.migrations }}
      assistant: ${{ inputs.assistant }}
      knowledge: ${{ inputs.knowledge }}
      docs: ${{ false}}
      any-service: ${{ steps.filter.outputs.assistant || steps.filter.outputs.knowledge-search }}
      # infrastructure: ${{ steps.filter.outputs.infrastructure == 'true' }}
      # migrations: ${{ steps.filter.outputs.migrations == 'true' }}
      # assistant: ${{ steps.filter.outputs.assistant == 'true' }}
      # knowledge: ${{ steps.filter.outputs.knowledge == 'true' }}
      # docs: ${{ steps.filter.outputs.docs == 'true' }}
      # any-service: ${{ steps.filter.outputs.assistant || steps.filter.outputs.knowledge-search }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            infrastructure:
              - 'infrastructure/**/*.bicep'
            migrations:
              - 'assistant/src/DbUpMigrator/scripts/**/*.sql'
            assistant:
              - 'assistant/**'
            knowledge:
              - 'knowledge-search/**'
            docs:
              - 'docs/**/*.md'

  provision-infrastructure-staging:
    needs: detect-changes
    uses: ./.github/workflows/reusable-deploy-infrastructure.yml
    with:
      environment: staging
    secrets: inherit
    if: |
      (always() && needs.detect-changes.outputs.infrastructure == 'true')

  apply-migrations-staging:
    uses: ./.github/workflows/reusable-migrate-database.yml
    needs: [detect-changes, provision-infrastructure-staging]
    with:
      environment: staging
    secrets: inherit
    if: |
      (always() && needs.detect-changes.outputs.migrations == 'true' &&
      (needs.provision-infrastructure-staging.result == 'success' || needs.provision-infrastructure-staging.result == 'skipped'))

  prepare-build-matrix:
    runs-on: ubuntu-latest
    needs: detect-changes
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          matrix="[]"
          if [[ "${{ needs.detect-changes.outputs.assistant }}" == "true" ]]; then
            matrix=$(echo "$matrix" | jq -c '. += [{
              "component":"assistant",
              "resource-group":"aiasst-staging",
              "container-app-name":"aiasst-api",
              "image-name":"aiasst-api",
              "context":"./assistant",
              "file":"./assistant/Dockerfile"
            }]')
            matrix=$(echo "$matrix" | jq -c '. += [{
              "component":"cleanup-job",
              "resource-group":"aiasst-staging",
              "container-app-name":"aiasst-cleanup-job",
              "image-name":"aiasst-cleanup-job",
              "context":"./assistant",
              "file":"./assistant/Dockerfile.ConversationCleanupJob"
            }]')
          fi
          if [[ "${{ needs.detect-changes.outputs.knowledge }}" == "true" ]]; then
            matrix=$(echo "$matrix" | jq -c '. += [{
              "component":"knowledge",
              "resource-group":"aiasst-staging",
              "container-app-name":"aiasst-knowledge",
              "image-name":"aiasst-knowledge",
              "context":"./knowledge-search",
              "file":"./knowledge-search/Dockerfile"
            }]')
          fi
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  build-images:
    needs: [detect-changes, prepare-build-matrix]
    strategy:
      matrix:
        include: ${{ fromJson(needs.prepare-build-matrix.outputs.matrix) }}
    secrets: inherit
    uses: ./.github/workflows/reusable-build-docker.yml
    with:
      image-name: ${{ matrix.image-name }}
      context: ${{ matrix.context }}
      file: ${{ matrix.file }}
      image-tag: staging
    if: always() && ${{ needs.detect-changes.outputs.any-service == 'true' }}

  deploy-assistant-ca-staging:
    uses: ./.github/workflows/publish-container-app.yml
    needs: [build-images, apply-migrations-staging]
    with:
      environment: staging
      resource-group: aiasst-staging
      container-app-name: aiasst-api
      image-name: aiasst-knowledge:${{ github.sha }}
    secrets: inherit
    if: |
      always() &&
      (needs.build-images.result == 'success') &&
      (needs.apply-migrations-staging.result == 'success' || needs.apply-migrations-staging.result == 'skipped')

  deploy-knowledge-ca-staging:
    uses: ./.github/workflows/publish-container-app.yml
    needs: [build-images, apply-migrations-staging]
    with:
      environment: staging
      resource-group: aiasst-staging
      container-app-name: aiasst-knowledge
      image-name: aiasst-knowledge:${{ github.sha }}
    secrets: inherit
    if: |
      always() &&
      (needs.build-images.result == 'success') &&
      (needs.apply-migrations-staging.result == 'success' || needs.apply-migrations-staging.result == 'skipped')

  wait-for-production-approval:
    runs-on: ubuntu-latest
    environment: production-approval
    needs: [deploy-assistant-ca-staging, deploy-knowledge-ca-staging]
    if: |
      always() &&
      (needs.deploy-assistant-ca-staging.result == 'success' || needs.deploy-assistant-ca-staging.result == 'skipped') &&
      (needs.deploy-knowledge-ca-staging.result == 'success' || needs.deploy-knowledge-ca-staging.result == 'skipped')
    steps:
      - run: |
          echo "Waiting for production approval..."

  provision-infrastructure-production:
    needs: [detect-changes, wait-for-production-approval]
    uses: ./.github/workflows/reusable-deploy-infrastructure.yml
    with:
      environment: production
    secrets: inherit
    if: |
      (always() && needs.detect-changes.outputs.infrastructure == 'true')

  apply-migrations-production:
    needs: [detect-changes, provision-infrastructure-production]
    uses: ./.github/workflows/reusable-migrate-database.yml
    with:
      environment: production
    secrets: inherit
    if: |
      (always() && needs.detect-changes.outputs.migrations == 'true' &&
      (needs.provision-infrastructure-production.result == 'success' || needs.provision-infrastructure-production.result == 'skipped'))

  promote-images:
    needs: [prepare-build-matrix, build-images, apply-migrations-production]
    strategy:
      matrix:
        include: ${{ fromJson(needs.prepare-build-matrix.outputs.matrix) }}
    uses: ./.github/workflows/reusable-promote-docker.yml
    with:
      image-name: ${{ matrix.image-name }}
      image-tag: staging
      promote-to: production
    if: |
      (always() &&
      (needs.apply-migrations-production.result == 'success' || needs.apply-migrations-production.result == 'skipped'))

  deploy-assistant-ca-production:
    uses: ./.github/workflows/publish-container-app.yml
    needs: [promote-images, apply-migrations-production]
    with:
      environment: production
      resource-group: aiasst-production
      container-app-name: aiasst-api
      image-name: aiasst-knowledge:${{ github.sha }}
    secrets: inherit
    if: |
      always() &&
      (needs.promote-images.result == 'success') &&
      (needs.apply-migrations-production.result == 'success' || needs.apply-migrations-production.result == 'skipped')

  deploy-knowledge-ca-production:
    uses: ./.github/workflows/publish-container-app.yml
    needs: [promote-images, apply-migrations-production]
    with:
      environment: production
      resource-group: aiasst-production
      container-app-name: aiasst-knowledge
      image-name: aiasst-knowledge:${{ github.sha }}
    secrets: inherit
    if: |
      always() &&
      (needs.promote-images.result == 'success') &&
      (needs.apply-migrations-production.result == 'success' || needs.apply-migrations-production.result == 'skipped')
