name: Deploy Assistant

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy"
        required: true
        default: "assistant-v0.0.1"
      image_name:
        description: "Image name"
        required: true
        default: "assistant"
      context:
        description: "Context"
        required: true
        default: "./assistant"
      file:
        description: "File"
        required: true
        default: "./assistant/Dockerfile"

jobs:
  call-build-docker-image:
    uses: ./.github/workflows/reusable-build-docker.yml
    with:
      image-name: ${{ inputs.image_name }}
      version: ${{ inputs.version }}
      context: ${{ inputs.context }}
      file: ${{ inputs.file }}
  debug:
    runs-on: ubuntu-latest
    needs: call-build-docker-image
    steps:
      - run: |
          echo "Image name: ${{ needs.call-build-docker-image.outputs.image-name-with-digest }}"
