name: Deploy Assistant

on:
  push:
    tags:
      - "assistant-*"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Deploying assistant..."
