name: Generate Changelogs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "CHANGELOG.md"
  schedule:
    # Runs at 2pm UTC every Friday (change timezone if needed)
    - cron: "0 14 * * 5"

jobs:
  generate-changelogs:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: changelog-release.config.json
          manifest-file: .release-manifest.json
