name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.PAT }}
          config-file: release-please-config.json

  trigger-deploy:
    needs: release
    uses: ./.github/workflows/deploy.yml
    if: ${{ needs.release.outputs.release_created == 'true' || needs.release.outputs.prs_created == 'true' }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      environment: ${{ needs.release-please.outputs.release_created == 'true' && 'production' || 'staging' }}
      release_tag: ${{ needs.release-please.outputs.tag_name }}
    secrets: inherit
