name: Build Docker Image

on:
  workflow_call:
    inputs:
      image-name:
        description: "Image name"
        required: true
        type: string
      image-tag:
        description: "Image tag"
        required: true
        type: string
      set-latest-tag:
        description: "Set latest tag"
        required: false
        type: boolean
        default: true
      context:
        description: "Context"
        required: true
        type: string
      file:
        description: "File"
        required: true
        type: string
    outputs:
      image-name-with-digest:
        description: "Image name with digest"
        value: ${{ jobs.build.outputs.image-name-with-digest }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-name-with-digest: ${{ steps.set-image-name.outputs.image-name-with-digest }}
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ inputs.set-latest-tag }}
            type=raw,value=${{ inputs.image-tag }},enable=${{ inputs.set-latest-tag != '' }}
            type=sha,format=long
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
      - uses: docker/build-push-action@v6
        id: build-push
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: true
          provenance: mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - id: set-image-name
        run: |
          IMAGE_NAME=${{ env.IMAGE_NAME }}:${{ steps.build-push.outputs.digest }}
          echo "image-name-with-digest=$IMAGE_NAME" >> $GITHUB_OUTPUT
